### ISSUE TITLE
How to import info-nce-pytorch

### ISSUE THREAD

**Issue by Skywalker-Harrison** [RElbers/info-nce-pytorch#14]
Hi, I am a new to contrastive learning, when I installed the package by using `pip install info-nce-pytorch` on my server, I could not import the package by using `from info-nce-pytorch import InfoNCE()`, could you tell me the name to import the package?
![image](https://github.com/RElbers/info-nce-pytorch/assets/63527319/fb6bcded-05f0-4376-ad33-b7966928cf56)

**Comment by pulkitkumar95** [comment]
`from info_nce import InfoNCE`

**Comment by Skywalker-Harrison** [comment]
> `from info_nce import InfoNCE`

Thank you!
